Dockerfile
This fixes a small typo that was causing kustomize generation to fail.
=> fix: ensure releases are build properly

controllers/taloscontrolplane_controller.go
This PR makes sure that the control-plane and cluster labels are applied
to machines that get created. We're supposed to be doing this anyways
and it enables us to filter by label in e2e soon.
=> fix: ensure machines get proper labels

controllers/taloscontrolplane_controller.go, main.go
This PR fixes a bug where we weren't passing in a failure domain for
control plane nodes when they get created.
=> fix: ensure we select a failure domain for clusters that support it

.drone.yml, controllers/taloscontrolplane_controller.go
This PR updates the deletion portion of the control plane provider to
also trigger deletion of any control plane machines in the cluster. This
mimics the behavior done in the kubeadm control plane provider.
Additionally, there were some updates to the way we add ownerrefs to
make sure that the refs are created with blockOwnerDeletion set to true
to make sure the full cluster can't get torn down without tearing down
these decendents.
=> fix: ensure cleanup happens properly

controllers/taloscontrolplane_controller.go, go.mod
This PR fixes a bug we were seeing where the ownerref that was getting
created by the taloscontrolplane was using a helper function and that
function set the controller: true in the ownerref. This keeps CAPI from
adding its own Machine ownerref to a given talosconfig because it
expects to be the controller for it.
=> fix: ensure talosconfigs are created w/o controller=true in ownerref

config/manager/manager.yaml
We should always be pulling the control plane provider image.
Will close #21
=> chore: update image pull policy

Dockerfile, controllers/taloscontrolplane_controller.go
The workflow now tries to validate the state of etcd on the node. This allows for multiple
reconciliations.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
=> fix: address scale down issues

CHANGELOG.md
This is the official v0.1.0-alpha.7 release.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
=> release(v0.1.0-alpha.7): prepare release

controllers/taloscontrolplane_controller.go, go.mod, go.sum
We should never directly use unwrapped client as it doesn't do filtering
for errors correctly. This wasn't that important in this particular
case, as client was connecting directly to the endpoint and it doesn't
set 'nodes' context, but it sets bad example.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
=> fix: use Talos API client correctly (wrapped version)

config/manager/manager.yaml
This PR updates the resource limits for this provider. Users saw issues
where the previously set values were too small when being used at scale
and causing OOM killing.
=> fix: update resources for deployment

config/manager/manager.yaml
This fixes an issue where we can't install on a 2 CPU/2GB RAM
node. Backing down the requests so that the pods can get scheduled, but
still keeping the limits high.
=> fix: back down resource requests

config/manager/manager.yaml
As we don't deploy kube-rbac-proxy, protect metrics-addr by binding to
the localhost.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
=> fix: protect metrics-addr by default

go.mod, go.sum
This PR updates cabpt to v0.2.0
=> chore: update bootstrap provider to stable release

controllers/configs.go, controllers/etcd.go, controllers/taloscontrolplane_controller.go, go.mod, go.sum, hack/test/e2e-aws.sh, internal/integration/integration_test.go
Fixes:
- Check etcd health on all nodes before scaling down.
- Check all nodes are booted before scaling down.
- Do not call `Shutdown` during machine deletion (only for Talos >= 0.12.2).
Scale down tests are disabled for Talos < 0.12.2.
=> test: implement scale up and down tests and fix found issues

config/metadata/metadata.yaml, internal/integration/integration_test.go
This PR makes sure we'll generate a working metadata for clusterctl to
use for the v0.2 release series.
=> fix: update metadata.yaml for v0.2 of CACPPT

Dockerfile, Makefile, controllers/configs.go
There was a bug in talosconfig iteration nested loop that `break` was
just stopping the internal loop.
Also allow building the container with race enabled.
=> fix: properly pick talos client configuration

.drone.yml, api/v1alpha3/conditions.go, api/v1alpha3/taloscontrolplane_types.go, config/crd/bases/controlplane.cluster.x-k8s.io_taloscontrolplanes.yaml, controllers/configs.go, controllers/consts.go, controllers/etcd.go, controllers/health.go, controllers/taloscontrolplane_controller.go, go.mod, go.sum, hack/test/e2e-aws.sh, internal/integration/integration_test.go
Fixes: https://github.com/talos-systems/cluster-api-control-plane-provider-talos/issues/74
That required couple changes in the manager flow:
- no longer get node IPs using `kubectl get nodes`, but use machines
addresses instead.
- add `MachinesBootstrapped` condition that means that `bootstrap` was
called on one of the machines.
=> feat: get rid of init nodes and use bootstrap API to setup cluster

controllers/taloscontrolplane_controller.go, internal/integration/integration_test.go
Doing that is pretty pointless as it's going to destroy a cluster.
Instead of doing that cluster should be deleted and recreated.
And with the new approach without init nodes scaling cluster back up
won't be able to succeed as bootstrap is done only a single time.
Still allowing user to set replicas to zero, but block scaling in the
controller with error messages when there's only a single node
remaining.
=> fix: do not allow scaling down controlplane to zero

.drone.yml
Release builds publish artifacts to the `ghcr.io` repo, so we should
pull the image from there.
Not sure why it was working before.
=> fix: introduce a separate step for release builds

README.md, controllers/taloscontrolplane_controller.go, hack/test/e2e-aws.sh, internal/integration/integration_test.go
This PR bundles the backports for release-0.4 branch needed for v0.4.0-beta.1
See:
65043b7cf85407e9e4683dbda1d96083d9e1de45
e0041f6567a61a388f5e69769fe28924e4f4fe7f
=> backports: for v0.4.0-beta.1

controllers/etcd.go, controllers/taloscontrolplane_controller.go
This makes `Sidero` tests fail, because the controller gets too many
errors during the bootstrap, as we populate the address before `apid` is ready.
=> fix: avoid long backoff when trying to bootstrap the cluster

config/crd/bases/controlplane.cluster.x-k8s.io_taloscontrolplanes.yaml, controllers/taloscontrolplane_controller.go, internal/integration/integration_test.go
Refactor reconcile loop to resemble Kubeadm controlplane controller.
Now it tries to reconcile: `etcd status`, `nodes health`, `bootstrap
status` and `kubeconfig` on each reconcile call.
This makes kubeconfig available much earlier and also different
reconcile phases do not cancel each other anymore.
=> fix: refactor reconcile loop

CHANGELOG.md
This is the official v0.4.2 release.
=> release(v0.4.2): prepare release

controllers/configs.go, controllers/etcd.go, controllers/health.go, controllers/taloscontrolplane_controller.go
This PR contains couple of fixes. In case if tcp has `init` nodes
config:
- mark controlplane as bootstrapped immediately.
- populate nodes kubeconfig using workload cluster nodes info instead of
using machines addresses.
=> fix: fall back to old scheme of getting talsoconfig for older templates

config/certmanager/certificate.yaml, config/default/kustomization.yaml
Bump cert-manager to `v1`
Signed-off-by: Noel Georgi <git@frezbo.dev>
=> chore: bump cert-manager to v1

config/certmanager/certificate.yaml, config/default/kustomization.yaml, controllers/configs.go
See:
https://github.com/talos-systems/cluster-api-control-plane-provider-talos/pull/108
https://github.com/talos-systems/cluster-api-control-plane-provider-talos/pull/110
=> backports: for v0.4.5

CHANGELOG.md, hack/release.toml
This is the official v0.4.5 release.
=> release(v0.4.5): prepare release

Dockerfile, Makefile, PROJECT, internal/integration/integration_test.go
Go module import paths still use talos-systems, go.mod module path is
updated.
Introduce url replacement for CABPT in the integration tests.
=> chore: rename github organization to siderolabs

README.md
This PR adds a blurb for overriding the clusterctl yaml to work after
our rename
=> docs: add note for clusterctl rename bug

controllers/configs.go, controllers/etcd.go, controllers/taloscontrolplane_controller.go, main.go
Instead of creating workload cluster Kubernetes client each time and
closing it after that, use CAPI standard class to cache the client.
=> refactor: use cached client tracker in the provider

controllers/configs.go, controllers/etcd.go
When node is just joining the cluster, `etcd members` briefly returns a
node with an empty hostname. If the member is deleted in this state, it
breaks the etcd cluster build and breaks the cluster.
=> fix: skip nodes with empty hostname on etcd audit

controllers/taloscontrolplane_controller.go
This should resolve a problem when there's a "deadlock" between CAPI
core MachineController and CACPPT: CAPI core waits for the control plane
to be initialized to start watching workload cluster Nodes to pick up
`.spec.ProviderID` changes, while CACPPT relies on the MachineController
to update the Machine status.
=> fix: mark control plane as initialized as soon as endpoints are ready

.conform.yaml, api/v1alpha3/taloscontrolplane_webhook.go, config/webhook/manifests.yaml, main.go
Looks like it was just copy pasted from kubeadm webhook
=> fix: tcp webhook resource name and version

controllers/taloscontrolplane_controller.go
When comparing nodes list in the workload clsuter with machine count, we
can see more nodes than machines, so this check removes a case when
stats go weird:
```
NAME                    READY   INITIALIZED   REPLICAS   READY REPLICAS   UNAVAILABLE REPLICAS
management-cluster-cp   true    true          1          2                -1
```
=> fix: stop reporting negative unavailable replicas

controllers/taloscontrolplane_controller.go
Talos was labeling control plane nodes with both `control-plane` and
`master` labels since Talos 0.8, so it should be safe to do that change.
Talos 1.2.0 is supposed to drop legacy `master` label, so we need to
make sure CACCPT is ready.
=> fix: use 'control-plane' Kubernetes node label

controllers/taloscontrolplane_controller.go
Talos was labeling control plane nodes with both `control-plane` and
`master` labels since Talos 0.8, so it should be safe to do that change.
Talos 1.2.0 is supposed to drop legacy `master` label, so we need to
make sure CACCPT is ready.
(cherry picked from commit 6fdde729b8551eef897756f42f9bfc0030855623)
=> backport: fix: use 'control-plane' Kubernetes node label

config/rbac/role.yaml, controllers/taloscontrolplane_controller.go
Fixes #126
Whenever kubeconfig reaches 50% of expiration, regenerate the secret.
This secret is used my many other CAPI components, so it needs to be up to date.
=> fix: regenerate kubeconfig on expiration

CHANGELOG.md, hack/release.toml
This is the official v0.4.11 release.
=> release(v0.4.11): prepare release

.gitignore, config/manager/kustomization.yaml, tilt-provider.json
This adds the support for [Tilt](https://tilt.dev), as described in https://cluster-api.sigs.k8s.io/developer/tilt.html#tilt-provider-configuration
Signed-off-by: Benjamin Gentil <benjamin.gentil@infomaniak.com>
=> feat: add Tilt support

controllers/scale.go
Fixes: https://github.com/siderolabs/cluster-api-control-plane-provider-talos/issues/155
We were reading it from `*int` pointer without dereferencing it, so it was writing pointer address to the status instead of the actual value.
=> fix: desired replicas count in scale conditions

api/v1alpha3/taloscontrolplane_types.go, controllers/scale.go, controllers/taloscontrolplane_controller.go, controllers/upgrade.go
This change does a nil check on the int32 ptr specifying the number of replica's inside the TalosControlPlane spec.
Slightly refactored version of https://github.com/siderolabs/cluster-api-control-plane-provider-talos/pull/158
=> fix: nil check replicas ptr before de-referencing

controllers/taloscontrolplane_controller.go
Looks like the logger extracts only stacktrace from the error passed as the first argument.
Additionally log error as the separate field.
=> fix: log actual error message in the reconcile error

controllers/etcd.go, controllers/health.go, controllers/taloscontrolplane_controller.go
PRs:
- https://github.com/siderolabs/cluster-api-control-plane-provider-talos/pull/168
- https://github.com/siderolabs/cluster-api-control-plane-provider-talos/pull/167
=> Backports to 0.5.1

controllers/scale.go
With Sidero Metal, deleting a machine leads to a super fast power down, and etcd leave doesn't have time to run, which breaks scaling down `2->1`.
=> fix: attempt etcd leave before deleting a Machine

controllers/controllers_test.go, controllers/etcd.go, controllers/helpers_test.go
Fixes: https://github.com/siderolabs/cluster-api-control-plane-provider-talos/issues/185
Lowercase etcd member hostname when comparing it with the CAPI one.
=> fix: properly handle uppercase hostnames in the etcd audit flow

main.go
See https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/issues/185
=> fix: set a default controller runtime log

controllers/taloscontrolplane_controller.go
This is so that harvester for lb and others that rely on this label has it.
=> Propagate ControlPlane label

.drone.yml, Dockerfile, config/crd/patches/webhook_in_taloscontrolplanes.yaml
See https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/pull/195
Also fix the local release assets path, so that provider is local-installable.
=> fix: remove CA bundle

CHANGELOG.md
This is the official v0.5.9 release.
Fixes https://github.com/siderolabs/talos/issues/10726
=> release(v0.5.9): prepare release
