- README.md
This PR brings in basic info about the provider.
> chore: add readme info

- controllers/taloscontrolplane_controller.go
This PR fixes a bug where the metalmachinetemplates that were associated
with a taloscontrolplane weren't getting a cluster ownerref and thus
weren't coming along for the `clusterctl move` ride.
> fix: ensure infra templates get labeled

- CHANGELOG.md
- hack/chglog/CHANGELOG.tpl.md
- hack/chglog/config.yml
- hack/release.sh
This is the official v0.1.0-alpha.1 release.
> release(v0.1.0-alpha.1): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.2 release.
> release(v0.1.0-alpha.2): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.4 release.
> release(v0.1.0-alpha.4): prepare release

- controllers/taloscontrolplane_controller.go
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> fix: scale down the control plane

- controllers/taloscontrolplane_controller.go
We don't have to wait to requeue.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> fix: remove requeue time

- CHANGELOG.md
This is the official v0.1.0-alpha.5 release.
> release(v0.1.0-alpha.5): prepare release

- controllers/taloscontrolplane_controller.go
This PR bypasses the defer func we were depending on to update the
finalizers. We now update the controlplane object manually and return before the
defer occurs. We'll eventually get rid of the defers altogether.
> fix: ensure we handle finalizer removal properly

- CHANGELOG.md
This is the official v0.1.0-alpha.6 release.
> release(v0.1.0-alpha.6): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.8 release.
> release(v0.1.0-alpha.8): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.9 release.
> release(v0.1.0-alpha.9): prepare release

- controllers/taloscontrolplane_controller.go
This PR updates the way we determine that our controlplanes are
initialized. We now say we're initialized if any nodes are registered
in the workload cluster.
This was needed because of an upstream change in moving to "phases" for
cluster api. We hit issues because we were saying that we were
initialized too early and that lead to a case where CAPI upstream would
never set the data secrets for a machine.
> fix: update initialization for CAPI v0.3.11

- CHANGELOG.md
This is the official v0.1.0-alpha.10 release.
> release(v0.1.0-alpha.10): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.11 release.
> release(v0.1.0-alpha.11): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.12 release.
> release(v0.1.0-alpha.12): prepare release

- CHANGELOG.md
This is the official v0.1.0-alpha.13 release.
> release(v0.1.0-alpha.13): prepare release

- controllers/taloscontrolplane_controller.go
This PR fixes some spots where we were importing the same libraries
multiple times under different names.
> chore: remove duplicate imports

- controllers/configs.go
- controllers/etcd.go
- controllers/taloscontrolplane_controller.go
This PR breaks out etcd and configfile functions from the main
controller code. It's mostly just a readability and DRY change as I was
getting confused when dealing with it. I'll be building on the etcd file
with my next PR.
> chore: breakout common functions

- CHANGELOG.md
- go.mod
- go.sum
This is the official v0.1.0-beta.0 release. It also pulls in the beta
release of our bootstrap provider.
> release(v0.1.0-beta.0): prepare release

- controllers/configs.go
- controllers/etcd.go
- controllers/taloscontrolplane_controller.go
Removing edge cases, simplifying code a bit.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
> fix: clean up couple small issues in the etcd member audit code

- controllers/configs.go
- controllers/etcd.go
- controllers/taloscontrolplane_controller.go
Removing edge cases, simplifying code a bit.
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
(cherry picked from commit 119b969be2fe152a0e8a63d189563deed55110b4)
> backport: fix: clean up couple small issues in the etcd member audit code

- CHANGELOG.md
- hack/release.toml
This is the official v0.3.0-alpha.0 release.
> release(v0.3.0-alpha.0): prepare release

- CHANGELOG.md
- hack/test/e2e-aws.sh
This is the official v0.4.0-alpha.0 release.
> release(v0.4.0-alpha.0): prepare release

- CHANGELOG.md
- README.md
- hack/release.toml
This is the official v0.4.0-beta.0 release.
> release(v0.4.0-beta.0): prepare release

- hack/test/e2e-aws.sh
- internal/integration/integration_test.go
This PR lets us test with the v1beta1 templates.
> test: update templates to v1beta1

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.0-beta.1 release.
> release(v0.4.0-beta.1): prepare release

- controllers/taloscontrolplane_controller.go
- main.go
This should hopefully avoid getting into split-brain.
> fix: patch the status and use APIReader to get resource

- CHANGELOG.md
This is the official v0.4.0-beta.2 release.
> release(v0.4.0-beta.2): prepare release

- CHANGELOG.md
This is the official v0.4.0 release.
> release(v0.4.0): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.1 release.
> release(v0.4.1): prepare release

- CHANGELOG.md
This is the official v0.4.3 release.
> release(v0.4.3): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.4 release.
> release(v0.4.4): prepare release

- controllers/configs.go
This should address the issue when the management plane was migrated by
using `clusterctl move`, which drops all statuses and talosconfig
resources become empty.
> fix: get talosconfig from secrets instead of talosconfig resources

- controllers/taloscontrolplane_controller.go
Closes https://github.com/siderolabs/cluster-api-control-plane-provider-talos/issues/130
> fix: fallback to ExternalIP for bootstrap if no InternalIP is found for the machine

- .conform.yaml
- CHANGELOG.md
- hack/release.toml
This is the official v0.4.7 release.
> release(v0.4.7): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.8 release.
> release(v0.4.8): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.9 release.
> release(v0.4.9): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.4.10 release.
> release(v0.4.10): prepare release

- .conform.yaml
- CHANGELOG.md
- README.md
- config/crd/bases/controlplane.cluster.x-k8s.io_taloscontrolplanes.yaml
- config/metadata/metadata.yaml
- hack/release.toml
This is the official v0.5.0-alpha.0 release.
> release(v0.5.0-alpha.0): prepare release

- .drone.yml
- CHANGELOG.md
- Makefile
- go.mod
This is the official v0.5.0-alpha.1 release.
> release(v0.5.0-alpha.1): prepare release

- controllers/controllers_test.go
- controllers/controlplane.go
This change automatically rolls out new Machines when the controlPlaneConfig has been changed.
> feat: trigger rollout on controlPlaneConfig changes

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.0-alpha.2 release.
> release(v0.5.0-alpha.2): prepare release

- .conform.yaml
- CHANGELOG.md
- hack/release.toml
This is the official v0.5.0 release.
> release(v0.5.0): prepare release

- CHANGELOG.md
- hack/release.sh
This is the official v0.5.2 release.
> release(v0.5.2): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.4 release.
> release(v0.5.4): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.6 release.
> release(v0.5.6): prepare release

- CHANGELOG.md
This is the official v0.5.8 release.
> release(v0.5.8): prepare release

- .github/workflows/ci.yaml
- .kres.yaml
Build both amd64 and arm64 images on tag event.
Fixes: #217
> fix(ci): arm64 container image asset

- CHANGELOG.md
- hack/release.toml
This is the official v0.5.10 release.
> release(v0.5.10): prepare release

- .secrets.yaml
Rotate the AWS IAM credentials for CI.
> chore: rotate aws iam credentials
